name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t jenkins-cicd-app .

      - name: Test Docker image
        run: docker run --rm jenkins-cicd-app nginx -t

      - name: Run Docker container
        run: docker run -d --name test-container -p 8082:80 jenkins-cicd-app

      - name: Test application
        run: curl --fail http://localhost:8082

      - name: Stop container
        run: docker stop test-container